// 🦕 AUTOGENERATED! DO NOT EDIT! File to edit: config.ipynb

import { ActorView } from "tinychat/api/types/chat/tinychat/actor/defs.ts";

export const getNotificationsWsUrl = (params?: {
  appViewUrl?: string | undefined;
  user?: ActorView | undefined;
}) => {
  const { appViewUrl, user } = Object.assign({
    appViewUrl: Deno.env.get("APPVIEW_URL")!,
  }, params);
  const base = `${appViewUrl.replace(/\/$/ig, "")}`.replace("http", "ws");
  return `${base}/ws` + (user ? `?did=${encodeURIComponent(user.did)}` : "");
};

/** ----------------tests ---------------- **/

import { assertEquals } from "asserts";
// 🦕 AUTOGENERATED! DO NOT EDIT! File to edit: config.ipynb

Deno.test("getNotificationsWsUrl", () => {
  assertEquals(getNotificationsWsUrl(), "ws://localhost:8001/ws");
  assertEquals(
    getNotificationsWsUrl({ appViewUrl: "https://appview.tinychat.chat" }),
    "wss://appview.tinychat.chat/ws",
  );
  assertEquals(
    // @ts-ignore yolo
    getNotificationsWsUrl({ user: { did: "did:hello" } }),
    "ws://localhost:8001/ws?did=did%3Ahello",
  );
});
