// 🦕 AUTOGENERATED! DO NOT EDIT! File to edit: config.ipynb

export const getNotificationsWsUrl = (
  appViewUrl: string = Deno.env.get("APPVIEW_URL")!,
) => {
  const base = `${appViewUrl.replace(/\/$/ig, "")}`.replace("http", "ws");
  return `${base}/ws`;
};

/** ----------------tests ---------------- **/

import { assert } from "asserts";
// 🦕 AUTOGENERATED! DO NOT EDIT! File to edit: config.ipynb

Deno.test("getNotificationsWsUrl", () => {
  assert(getNotificationsWsUrl() === "ws://localhost:8001/ws");
  assert(
    getNotificationsWsUrl("https://appview.tinychat.chat") ===
      "wss://appview.tinychat.chat/ws",
  );
});
