// 🦕 AUTOGENERATED! DO NOT EDIT! File to edit: config.ipynb

export const getNotificationsWsUrl = (
  appViewUrl: string = Deno.env.get("APPVIEW_URL")!,
) => {
  const base = `${appViewUrl.replace(/\/$/ig, "")}`.replace("http", "ws");
  return `${base}/ws`;
};
