import { Record as Message } from "tinychat/api/types/chat/tinychat/core/message.ts";
import { MessageView as BaseMessageView } from "tinychat/api/types/chat/tinychat/core/defs.ts";
// 🦕 AUTOGENERATED! DO NOT EDIT! File to edit: core/base.ipynb

export {
  validateMessageView,
} from "tinychat/api/types/chat/tinychat/core/defs.ts";

export type MessageView = BaseMessageView & {
  record: Message;
};
