import { ValidationResult } from "@atproto/lexicon";
import {
  Record as Message,
  validateRecord,
} from "@tinychat/lexicons/types/chat/tinychat/core/message.ts";
import {
  MessageView as BaseMessageView,
  validateMessageView as baseValidateMessageView,
} from "@tinychat/lexicons/types/chat/tinychat/core/defs.ts";
// 🦕 AUTOGENERATED! DO NOT EDIT! File to edit: core/base.ipynb

export type MessageView = BaseMessageView & {
  record: Message;
};

export const validateMessageView = (view: unknown): ValidationResult => {
  const r = baseValidateMessageView(view);
  if (!r.success) return r;
  // validate underlying message record inside record
  // @ts-ignore yolo
  const rr = validateRecord(view.record);
  if (!rr.success) return rr;
  return r;
};
