// 🦕 AUTOGENERATED! DO NOT EDIT! File to edit: core/servers.ipynb

import type { Database } from "tinychat/db.ts";
import { TID } from "@atproto/common";
import { fetchView, seedMessages, waitForSync } from "tinychat/db.ts";
import {
  DeleteMembershipRecord,
  DeleteServerRecord,
  NewMembershipRecord,
  NewServerRecord,
} from "tinychat/firehose.ts";
import {
  ServerSummaryView,
  ServerView,
  validateServerSummaryView,
  validateServerView,
} from "tinychat/api/types/chat/tinychat/server/defs.ts";
import { TinychatAgent } from "tinychat/agent.ts";

export class Servers {
  constructor(protected db: Database) {}

  async createServer(
    { name, tc }: { name: string; tc: TinychatAgent },
  ): Promise<ServerView> {
    const { uri } = await waitForSync<{ uri: string }>({
      db: this.db,
      op: () => {
        return tc.chat.tinychat.core.server.create(
          {
            repo: tc.agent.assertDid,
          },
          {
            name,
            channels: [
              { name: "general", id: TID.nextStr() },
              { name: "random", id: TID.nextStr() },
              { name: "meta", id: TID.nextStr() },
            ],
          },
        );
      },
      sql: ({ uri }) => `SELECT uri FROM servers WHERE uri = '${uri}'`,
    });

    return (await this.getServers({ uris: [uri] }))[0];
  }

  async joinServer(
    { server, tc }: { server: string; tc: TinychatAgent },
  ): Promise<{ uri: string }> {
    return await waitForSync<{ uri: string }>({
      db: this.db,
      op: () => {
        return tc.chat.tinychat.core.membership.create(
          { repo: tc.agent.assertDid },
          {
            server,
            createdAt: new Date().toISOString(),
          },
        );
      },
      sql: ({ uri }) =>
        `SELECT uri FROM server_memberships WHERE uri = '${uri}'`,
    });
  }

  syncServer(server: NewServerRecord) {
    const createChannel = this.db.prepare(
      `INSERT INTO channels (id, name, server) VALUES (:id, :name, :server) ON CONFLICT(id, server) DO NOTHING`,
    );

    this.db.transaction(() => {
      this.db
        .prepare(
          `
        INSERT INTO servers (uri, name, creator) VALUES (
          :uri, :name, :creator
        )`,
        )
        .run({
          uri: server.uri,
          name: server.commit.record.name,
          creator: server.did,
        });

      // this.db
      //   .prepare(
      //     `INSERT INTO server_memberships (user, server) VALUES (
      //       :creator, :server
      //     ) ON CONFLICT(user, server) DO NOTHING`,
      //   )
      //   .run({ creator: server.did, server: server.uri });

      for (const channel of server.commit.record.channels) {
        createChannel.run({
          id: channel.id,
          name: channel.name,
          server: server.uri,
        });
      }
    })();

    // seed messages if needed
    if (Deno.env.get("SEED_MESSAGES_AFTER_SERVER_CREATION")) {
      setTimeout(() => {
        seedMessages({ db: this.db, server: server.uri });
      }, 1000);
    }
  }

  public createMembership(m: NewMembershipRecord) {
    this.db.prepare(
      `INSERT INTO server_memberships (user, server, uri) VALUES (
        :user, :server, :uri
      )`,
    ).run({
      uri: m.uri,
      user: m.did,
      server: m.commit.record.server,
    });
  }

  deleteServer(server: DeleteServerRecord) {
    this.db.prepare(`DELETE FROM servers WHERE uri = '${server.uri}'`).run();
  }

  deleteMembership(membership: DeleteMembershipRecord) {
    this.db
      .prepare(
        `DELETE FROM server_memberships WHERE user = '${membership.did}' AND server = '${membership.uri}'`,
      )
      .run();
  }

  public getServers({
    uris,
    did,
  }: // viewer,
    {
      uris?: string[] | undefined;
      did?: string | undefined;
      viewer?: string | undefined;
    }): ServerView[] {
    let baseWhere = "";
    if (uris && uris.length > 0) {
      baseWhere = `uri IN (${uris.map((u) => `'${u}'`).join(", ")})`;
    } else if (did) {
      baseWhere = `creator__did = '${did}'`;
    }

    // viewer ? `viewer = '${viewer}'` : "",
    const where = [baseWhere]
      .filter((q) => q)
      .join(" AND ")
      .trim();

    return fetchView<ServerView>({
      db: this.db,
      // sql: `SELECT * FROM ${viewer ? 'server_view_with_viewer' : 'server_view'} ${where ? `WHERE ${where}` : ""}`,
      sql: `SELECT * FROM  server_view ${where ? `WHERE ${where}` : ""}`,
      validate: validateServerView,
    });
  }

  public getServersForMember({ did }: { did: string }): ServerView[] {
    return fetchView<ServerView>({
      db: this.db,
      sql: `SELECT * FROM server_with_members_view WHERE member = '${did}'`,
      validate: validateServerView,
    });
  }

  public findServers(
    { query }: { query?: string | undefined },
  ): ServerSummaryView[] {
    console.log("Finding servers with query: ", query);
    return fetchView<ServerSummaryView>({
      db: this.db,
      sql: "SELECT * FROM  server_view",
      validate: validateServerSummaryView,
    });
  }
}
