name: PRs

on:
  pull_request:
env:
  SESSION_COOKIE_KEY: ${{ secrets.SESSION_COOKIE_KEY }}
  SESSION_COOKIE_ALLOW_INSECURE: ${{ secrets.SESSION_COOKIE_ALLOW_INSECURE }}
  PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
  APPVIEW_URL: ${{ secrets.APPVIEW_URL }}
  JETSTREAM_URL: ${{ secrets.JETSTREAM_URL }}
  JETSTREAM_WANTED_COLLECTIONS: ${{ secrets.JETSTREAM_WANTED_COLLECTIONS }}

jobs:
  build:
    uses: callmephilip/jurassic/.github/workflows/build.yml@main
