name: PRs

on:
  pull_request:
env:
  SESSION_COOKIE_KEY: ${{ secrets.SESSION_COOKIE_KEY }}
  SESSION_COOKIE_ALLOW_INSECURE: ${{ secrets.SESSION_COOKIE_ALLOW_INSECURE }}
  PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

jobs:
  build:
    uses: callmephilip/jurassic/.github/workflows/build.yml@main
