name: Publish
on:
  push:
    branches:
      - main
env:
  SESSION_COOKIE_KEY: ${{ secrets.SESSION_COOKIE_KEY }}
  SESSION_COOKIE_ALLOW_INSECURE: ${{ secrets.SESSION_COOKIE_ALLOW_INSECURE }}
  PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    uses: callmephilip/jurassic/.github/workflows/build.yml@main
    secrets: inherit
  docs:
    uses: callmephilip/jurassic/.github/workflows/docs.yml@main
    secrets: inherit
