name: Publish
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: see if env vars propagate OK
        run: echo $PUBLIC_URL
  build:
    uses: callmephilip/jurassic/.github/workflows/build.yml@main
    env:
      SESSION_COOKIE_KEY: ${{ secrets.SESSION_COOKIE_KEY }}
      SESSION_COOKIE_ALLOW_INSECURE: ${{ secrets.SESSION_COOKIE_ALLOW_INSECURE }}
      PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

  docs:
    uses: callmephilip/jurassic/.github/workflows/docs.yml@main
    env:
      SESSION_COOKIE_KEY: ${{ secrets.SESSION_COOKIE_KEY }}
      SESSION_COOKIE_ALLOW_INSECURE: ${{ secrets.SESSION_COOKIE_ALLOW_INSECURE }}
      PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

