name: Publish
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # build:
  #   uses: callmephilip/jurassic/.github/workflows/build.yml@main
  #   env:
  #     SESSION_COOKIE_KEY: ${{ secrets.SESSION_COOKIE_KEY }}
  #     SESSION_COOKIE_ALLOW_INSECURE: ${{ secrets.SESSION_COOKIE_ALLOW_INSECURE }}
  #     PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

  # docs:
  #   uses: callmephilip/jurassic/.github/workflows/docs.yml@main
  #   env:
  #     SESSION_COOKIE_KEY: ${{ secrets.SESSION_COOKIE_KEY }}
  #     SESSION_COOKIE_ALLOW_INSECURE: ${{ secrets.SESSION_COOKIE_ALLOW_INSECURE }}
  #     PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
  deploy-client:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "tinychat"
          entrypoint: "client.tsx"
          root: "."
          exclude: |
            "**/node_modules"
            "_docs"
            "nbs"